##
# Board architecture
##
ARG IMAGE_ARCH=

##
# The registry and the namespace
##
ARG BASE_REGISTRY=

##
# Base container image name
##
ARG BASE_IMAGE=

##
# Base container version
##
ARG BASE_VERSION=

##
# GPU prefix
##
ARG GPU=


FROM --platform=linux/${IMAGE_ARCH} \
    ${BASE_REGISTRY}${BASE_IMAGE}${GPU}:${BASE_VERSION} AS Build

ARG IMAGE_ARCH
ARG GPU
ARG BASE_VERSION

RUN apt-get -q -y update  \
        && apt-get -q -y install openssl \
        openssh-server \
        rsync \
        file \
        git \
        libegl1-mesa-dev \
        libgl1-mesa-dev \
        build-essential \
        g++ \
        automake \
        autoconf \
        libtool \
        pkg-config \
        m4 \
        libbz2-dev \
        libzstd-dev \
        default-libmysqlclient-dev \
        unixodbc-dev \
        libpq-dev \
        libsqlite3-dev \
        libglib2.0-dev \
        libcurl4-gnutls-dev \
        libgtkglext1-dev \
        libpcre3-dev \
        libsdl-sound1.2-dev \
        libsdl-mixer1.2-dev \
        libsdl-image1.2-dev \
        libxml2-dev \
        libxslt1-dev \
        librsvg2-dev \
        libpoppler-dev \
        libpoppler-glib-dev \
        libpoppler-private-dev \
        libpoppler-cpp-dev \
        libasound2-dev \
        libdirectfb-dev \
        libxtst-dev \
        libffi-dev \
        libglew-dev \
        libimlib2-dev \
        libv4l-dev \
        libsdl-ttf2.0-dev \
        libgdk-pixbuf2.0-dev \
        linux-libc-dev \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        libcairo2-dev \
        libgsl-dev \
        libncurses5-dev \
        libgmime-3.0-dev \
        libalure-dev \
        libgmp-dev \
        libgtk-3-dev \
        libsdl2-dev \
        libsdl2-mixer-dev \
        libsdl2-ttf-dev \
        libsdl2-image-dev \
        sane-utils \
        libdumb1-dev \
        libqt5opengl5-dev \
        libqt5svg5-dev \
        libqt5webkit5-dev \
        libqt5x11extras5-dev \
        qtbase5-dev \
        qtwebengine5-dev \
        libwebkit2gtk-4.0-dev \
        libssl-dev \
        && apt-get clean  \
        && apt-get autoremove  \
        && rm -rf /var/lib/apt/lists/*

RUN git clone https://gitlab.com/microhobby/gambas.git  \
        && cd gambas  \
        && git checkout microhobby-stable \
        && ./reconf-all  \
        && GAMBAS_CONFIG_FAILURE=1 ./configure -C --disable-keyring --disable-sqlite2 --disable-qt4 --disable-qtwebkit  \
        && make -j$(nproc)  \
        && make DESTDIR=/install install

FROM --platform=linux/${IMAGE_ARCH} \
    ${BASE_REGISTRY}${BASE_IMAGE}${GPU}:${BASE_VERSION} AS Deploy

RUN apt-get -y update && apt-get install -y --no-install-recommends \
    libgtk-3-0 \
    librsvg2-2 \
        && apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

COPY --from=Build /install /install

RUN cp -RT /install/usr/ /usr/ && \
    rm -r /install && \
    ldconfig
